data:
  database:
    driver: "postgres"
    source: "host=localhost port=5432 user=postgres password=123456 dbname=example sslmode=disable"
    migrate: true

  redis:
    addr: "127.0.0.1:6379"
    password: "123456"
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s